export { default as London_Eye_1_Img } from './1.jpg'
export { default as London_Eye_2_Img } from './2.jpg'
export { default as London_Eye_3_Img } from './3.jpg'
export { default as London_Eye_4_Img } from './4.jpg'
export { default as London_Eye_5_Img } from './5.jpg'