export { default as De_Wallen_1_Img } from './1.jpg'
export { default as De_Wallen_2_Img } from './2.jpg'
export { default as De_Wallen_3_Img } from './3.jpg'
export { default as De_Wallen_4_Img } from './4.jpg'
export { default as De_Wallen_5_Img } from './5.jpg'