export { default as Supertree_Grove_1_Img } from './1.jpg'
export { default as Supertree_Grove_2_Img } from './2.jpg'
export { default as Supertree_Grove_3_Img } from './3.jpg'
export { default as Supertree_Grove_4_Img } from './4.jpg'
export { default as Supertree_Grove_5_Img } from './5.jpg'