export { default as Tower_of_London_1_Img } from './1.jpg'
export { default as Tower_of_London_2_Img } from './2.jpg'
export { default as Tower_of_London_3_Img } from './3.jpg'
export { default as Tower_of_London_4_Img } from './4.jpg'
export { default as Tower_of_London_5_Img } from './5.jpg'