export { default as Tour_Eiffel_1_Img } from './1.jpg'
export { default as Tour_Eiffel_2_Img } from './2.jpg'
export { default as Tour_Eiffel_3_Img } from './3.jpg'
export { default as Tour_Eiffel_4_Img } from './4.jpg'
export { default as Tour_Eiffel_5_Img } from './5.jpg'