export { default as Tour_Eiffel_Img } from './Tour_Eiffel/5.jpg'
export { default as Louvre_Img } from './Louvre/4.jpg'
export { default as Arc_de_Triomphe_Img } from './Arc_de_Triomphe/2.jpg'
export { default as Sainte_Chapelle_Img } from './Sainte_Chapelle/2.jpg'
export { default as Jardin_des_Tuileries_Img } from './Jardin_des_Tuileries/5.jpg'
export { default as Place_des_Vosges_Img } from './Place_des_Vosges/1.jpg'
export { default as Notre_Dame_de_Paris_Img } from './Notre_Dame_de_Paris/2.jpg'
export { default as Jardin_du_Luxembourg_Img } from './Jardin_du_Luxembourg/5.jpg'