export { default as Sainte_Chapelle_1_Img } from './1.jpg'
export { default as Sainte_Chapelle_2_Img } from './2.jpg'
export { default as Sainte_Chapelle_3_Img } from './3.jpg'
export { default as Sainte_Chapelle_4_Img } from './4.jpg'
export { default as Sainte_Chapelle_5_Img } from './5.jpg'