export { default as Singapore_Botanic_Gardens_1_Img } from './1.jpg'
export { default as Singapore_Botanic_Gardens_2_Img } from './2.jpg'
export { default as Singapore_Botanic_Gardens_3_Img } from './3.jpg'
export { default as Singapore_Botanic_Gardens_4_Img } from './4.jpg'
export { default as Singapore_Botanic_Gardens_5_Img } from './5.jpg'