export { default as Buckingham_Palace_1_Img } from './1.jpg'
export { default as Buckingham_Palace_2_Img } from './2.jpg'
export { default as Buckingham_Palace_3_Img } from './3.jpg'
export { default as Buckingham_Palace_4_Img } from './4.jpg'
export { default as Buckingham_Palace_5_Img } from './5.jpg'