export { default as Pantheon_1_Img } from './1.jpg'
export { default as Pantheon_2_Img } from './2.jpg'
export { default as Pantheon_3_Img } from './3.jpg'
export { default as Pantheon_4_Img } from './4.jpg'
export { default as Pantheon_5_Img } from './5.jpg'