export { default as Old_Town_Square_1_Img } from './1.jpg'
export { default as Old_Town_Square_2_Img } from './2.jpg'
export { default as Old_Town_Square_3_Img } from './3.jpg'
export { default as Old_Town_Square_4_Img } from './4.jpg'
export { default as Old_Town_Square_5_Img } from './5.jpg'