export { default as National_Gallery_1_Img } from './1.jpg'
export { default as National_Gallery_2_Img } from './2.jpg'
export { default as National_Gallery_3_Img } from './3.jpg'
export { default as National_Gallery_4_Img } from './4.jpg'
export { default as National_Gallery_5_Img } from './5.jpg'