export { default as Statue_of_Liberty_1_Img } from './1.jpg'
export { default as Statue_of_Liberty_2_Img } from './2.jpg'
export { default as Statue_of_Liberty_3_Img } from './3.jpg'
export { default as Statue_of_Liberty_4_Img } from './4.jpg'
export { default as Statue_of_Liberty_5_Img } from './5.jpg'