export { default as London_Img } from './London/attractions/Palace_of_Westminster/3.jpg'
export { default as Paris_Img } from './Paris/attractions/Tour_Eiffel/3.jpg'
export { default as New_York_Img } from './New_York/attractions/Statue_of_Liberty/3.jpg'
export { default as Rio_de_Janeiro_Img } from './Rio_de_Janeiro/attractions/Christ_the_Redeemer/2.jpg'
export { default as Prague_Img } from './Prague/attractions/Old_Town_Square/5.jpg'