export { default as Piazza_Navona_1_Img } from './1.jpg'
export { default as Piazza_Navona_2_Img } from './2.jpg'
export { default as Piazza_Navona_3_Img } from './3.jpg'
export { default as Piazza_Navona_4_Img } from './4.jpg'
export { default as Piazza_Navona_5_Img } from './5.jpg'