export { default as Rijksmuseum_1_Img } from './1.jpg'
export { default as Rijksmuseum_2_Img } from './2.jpg'
export { default as Rijksmuseum_3_Img } from './3.jpg'
export { default as Rijksmuseum_4_Img } from './4.jpg'
export { default as Rijksmuseum_5_Img } from './5.jpg'