export { default as Empire_State_Building_1_Img } from './1.jpg'
export { default as Empire_State_Building_2_Img } from './2.jpg'
export { default as Empire_State_Building_3_Img } from './3.jpg'
export { default as Empire_State_Building_4_Img } from './4.jpg'
export { default as Empire_State_Building_5_Img } from './5.jpg'