export { default as Cloud_Forest_Img } from './Cloud_Forest/2.jpg'
export { default as Marina_Bay_Sands_Img } from './Marina_Bay_Sands/5.jpg'
export { default as Supertree_Grove_Img } from './Supertree_Grove/4.jpg'
export { default as Jewel_Changi_Airport_Img } from './Jewel_Changi_Airport/5.jpg'
export { default as Singapore_Botanic_Gardens_Img } from './Singapore_Botanic_Gardens/3.jpg'