export { default as Sky_Garden_1_Img } from './1.jpg'
export { default as Sky_Garden_2_Img } from './2.jpg'
export { default as Sky_Garden_3_Img } from './3.jpg'
export { default as Sky_Garden_4_Img } from './4.jpg'
export { default as Sky_Garden_5_Img } from './5.jpg'