export { default as Cloud_Forest_1_Img } from './1.jpg'
export { default as Cloud_Forest_2_Img } from './2.jpg'
export { default as Cloud_Forest_3_Img } from './3.jpg'
export { default as Cloud_Forest_4_Img } from './4.jpg'
export { default as Cloud_Forest_5_Img } from './5.jpg'