export { default as Colosseum_1_Img } from './1.jpg'
export { default as Colosseum_2_Img } from './2.jpg'
export { default as Colosseum_3_Img } from './3.jpg'
export { default as Colosseum_4_Img } from './4.jpg'
export { default as Colosseum_5_Img } from './5.jpg'