export { default as Christ_the_Redeemer_1_Img } from './1.jpg'
export { default as Christ_the_Redeemer_2_Img } from './2.jpg'
export { default as Christ_the_Redeemer_3_Img } from './3.jpg'
export { default as Christ_the_Redeemer_4_Img } from './4.jpg'
export { default as Christ_the_Redeemer_5_Img } from './5.jpg'