export { default as Louvre_1_Img } from './1.jpg'
export { default as Louvre_2_Img } from './2.jpg'
export { default as Louvre_3_Img } from './3.jpg'
export { default as Louvre_4_Img } from './4.jpg'
export { default as Louvre_5_Img } from './5.jpg'