export { default as Westminster_Abbey_1_Img } from './1.jpg'
export { default as Westminster_Abbey_2_Img } from './2.jpg'
export { default as Westminster_Abbey_3_Img } from './3.jpg'
export { default as Westminster_Abbey_4_Img } from './4.jpg'
export { default as Westminster_Abbey_5_Img } from './5.jpg'