export { default as Charles_Bridge_1_Img } from './1.jpg'
export { default as Charles_Bridge_2_Img } from './2.jpg'
export { default as Charles_Bridge_3_Img } from './3.jpg'
export { default as Charles_Bridge_4_Img } from './4.jpg'
export { default as Charles_Bridge_5_Img } from './5.jpg'