export { default as Sugarloaf_Mountain_1_Img } from './1.jpg'
export { default as Sugarloaf_Mountain_2_Img } from './2.jpg'
export { default as Sugarloaf_Mountain_3_Img } from './3.jpg'
export { default as Sugarloaf_Mountain_4_Img } from './4.jpg'
export { default as Sugarloaf_Mountain_5_Img } from './5.jpg'