export { default as The_Shard_1_Img } from './1.jpg'
export { default as The_Shard_2_Img } from './2.jpg'
export { default as The_Shard_3_Img } from './3.jpg'
export { default as The_Shard_4_Img } from './4.jpg'
export { default as The_Shard_5_Img } from './5.jpg'