export { default as Foro_Romano_1_Img } from './1.jpg'
export { default as Foro_Romano_2_Img } from './2.jpg'
export { default as Foro_Romano_3_Img } from './3.jpg'
export { default as Foro_Romano_4_Img } from './4.jpg'
export { default as Foro_Romano_5_Img } from './5.jpg'