export { default as Prague_Castle_1_Img } from './1.jpg'
export { default as Prague_Castle_2_Img } from './2.jpg'
export { default as Prague_Castle_3_Img } from './3.jpg'
export { default as Prague_Castle_4_Img } from './4.jpg'
export { default as Prague_Castle_5_Img } from './5.jpg'