export { default as Copacabana_Beach_1_Img } from './1.jpg'
export { default as Copacabana_Beach_2_Img } from './2.jpg'
export { default as Copacabana_Beach_3_Img } from './3.jpg'
export { default as Copacabana_Beach_4_Img } from './4.jpg'
export { default as Copacabana_Beach_5_Img } from './5.jpg'