export { default as LondonImage } from './London.jpg'

export { TowerBridgeImage } from './TowerBridge'
export { BuckinghamPalaceImage } from './BuckinghamPalace'
export { BritishMuseumImage } from './BritishMuseum'
export { PalaceOfWestminsterImage } from './PalaceOfWestminster'
export { TowerOfLondonImage } from './TowerOfLondon'
export { HydeParkImage } from './HydePark'
export { LondonEyeImage } from './LondonEye'
export { NationalGalleryImage } from './NationalGallery'
export { HarrodsImage } from './Harrods'
export { SkyGardenImage } from './SkyGarden'
export { TheShardImage } from './TheShard'
export { WestminsterAbbeyImage } from './WestminsterAbbey'