export { default as Parque_Lage_1_Img } from './1.jpg'
export { default as Parque_Lage_2_Img } from './2.jpg'
export { default as Parque_Lage_3_Img } from './3.jpg'
export { default as Parque_Lage_4_Img } from './4.jpg'
export { default as Parque_Lage_5_Img } from './5.jpg'