export { default as Vondelpark_1_Img } from './1.jpg'
export { default as Vondelpark_2_Img } from './2.jpg'
export { default as Vondelpark_3_Img } from './3.jpg'
export { default as Vondelpark_4_Img } from './4.jpg'
export { default as Vondelpark_5_Img } from './5.jpg'