export { default as Van_Gogh_Museum_1_Img } from './1.jpg'
export { default as Van_Gogh_Museum_2_Img } from './2.jpg'
export { default as Van_Gogh_Museum_3_Img } from './3.jpg'
export { default as Van_Gogh_Museum_4_Img } from './4.jpg'
export { default as Van_Gogh_Museum_5_Img } from './5.jpg'